In [24]:
import os
import pandas as pd
import sqlite3
import numpy as np

In [2]:
os.getcwd()

'C:\\Users\\EMJOE\\Documents\\Workstation'

In [4]:
dbPath = "C:/sandbox"

In [5]:
os.chdir(dbPath)

In [6]:
os.getcwd()

'C:\\sandbox'

In [7]:
conn = sqlite3.connect('hubway.db')
cur = conn.cursor()

In [10]:
allTablesQuery = "select name from sqlite_master where type = 'table'"
cur.execute(allTablesQuery)
print(cur.fetchall())

[('instructor',), ('daibetes',), ('diamonds',)]


In [11]:
df = pd.read_csv('winequality-red_cleanout.csv')
df

Unnamed: 0  fixed acidity  volatile acidity  citric acid  \
0              0            7.4             0.700         0.00   
1              1            7.8             0.880         0.00   
2              2            7.8             0.760         0.04   
3              3           11.2             0.280         0.56   
4              4            7.4             0.700         0.00   
...          ...            ...               ...          ...   
1037        1592            6.3             0.510         0.13   
1038        1593            6.8             0.620         0.08   
1039        1594            6.2             0.600         0.08   
1040        1596            6.3             0.510         0.13   
1041        1597            5.9             0.645         0.12   

      residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  \
0                1.9      0.076                 11.0                  34.0   
1                2.6      0.098                 25.0                  67.0   
2                2.3      0.092                 15.0                  54.0   
3                1.9      0.075                 17.0                  60.0   
4                1.9      0.076                 11.0                  34.0   
...              ...        ...                  ...                   ...   
1037             2.3      0.076                 29.0                  40.0   
1038             1.9      0.068                 28.0                  38.0   
1039             2.0      0.090                 32.0                  44.0   
1040             2.3      0.076                 29.0                  40.0   
1041             2.0      0.075                 32.0                  44.0   

      density    pH  sulphates  alcohol  quality  
0     0.99780  3.51       0.56      9.4        5  
1     0.99680  3.20       0.68      9.8        5  
2     0.99700  3.26       0.65      9.8        5  
3     0.99800  3.16       0.58      9.8        6  
4     0.99780  3.51       0.56      9.4        5  
...       ...   ...        ...      ...      ...  
1037  0.99574  3.42       0.75     11.0        6  
1038  0.99651  3.42       0.82      9.5        6  
1039  0.99490  3.45       0.58     10.5        5  
1040  0.99574  3.42       0.75     11.0        6  
1041  0.99547  3.57       0.71     10.2        5  

[1042 rows x 13 columns]

In [14]:
dfCol = df.columns.tolist()
dfCol

['Unnamed: 0',
 'fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality']

In [21]:
len(dfCol)

13

In [18]:
createQuery = """create table winequality_red
(ID int,
fixedAcidity numeric,
volatileAcidity numeric,
citricAcid numeric,
residualSugar numeric,
chlorides numeric,
freeSulfurDioxide numeric,
totalSulfurDioxide numeric,
density numeric,
pH numeric,
sulphates numeric,
alcohol numeric,
quality int
)"""
cur.execute(createQuery)

In [20]:
tableQuery = "select * from winequality_red"
cur.execute(tableQuery)
sqlDF = pd.read_sql_query(tableQuery, conn)
sqlDF

Empty DataFrame
Columns: [ID, fixedAcidity, volatileAcidity, citricAcid, residualSugar, chlorides, freeSulfurDioxide, totalSulfurDioxide, density, pH, sulphates, alcohol, quality]
Index: []

In [22]:
#Converting dataframe to an array of array
dfRows = df.values
dfRows

array([[0.000e+00, 7.400e+00, 7.000e-01, ..., 5.600e-01, 9.400e+00,
        5.000e+00],
       [1.000e+00, 7.800e+00, 8.800e-01, ..., 6.800e-01, 9.800e+00,
        5.000e+00],
       [2.000e+00, 7.800e+00, 7.600e-01, ..., 6.500e-01, 9.800e+00,
        5.000e+00],
       ...,
       [1.594e+03, 6.200e+00, 6.000e-01, ..., 5.800e-01, 1.050e+01,
        5.000e+00],
       [1.596e+03, 6.300e+00, 5.100e-01, ..., 7.500e-01, 1.100e+01,
        6.000e+00],
       [1.597e+03, 5.900e+00, 6.450e-01, ..., 7.100e-01, 1.020e+01,
        5.000e+00]])

In [27]:
#Converting dataframe from an array of array to a list of list
dfListRows = list(dfRows)
dfListRows

[array([ 0.    ,  7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    ,
        34.    ,  0.9978,  3.51  ,  0.56  ,  9.4   ,  5.    ]),
 array([ 1.    ,  7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    ,
        67.    ,  0.9968,  3.2   ,  0.68  ,  9.8   ,  5.    ]),
 array([2.00e+00, 7.80e+00, 7.60e-01, 4.00e-02, 2.30e+00, 9.20e-02,
        1.50e+01, 5.40e+01, 9.97e-01, 3.26e+00, 6.50e-01, 9.80e+00,
        5.00e+00]),
 array([ 3.   , 11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,
         0.998,  3.16 ,  0.58 ,  9.8  ,  6.   ]),
 array([ 4.    ,  7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    ,
        34.    ,  0.9978,  3.51  ,  0.56  ,  9.4   ,  5.    ]),
 array([ 5.    ,  7.4   ,  0.66  ,  0.    ,  1.8   ,  0.075 , 13.    ,
        40.    ,  0.9978,  3.51  ,  0.56  ,  9.4   ,  5.    ]),
 array([ 6.    ,  7.9   ,  0.6   ,  0.06  ,  1.6   ,  0.069 , 15.    ,
        59.    ,  0.9964,  3.3   ,  0.46  ,  9.4   ,  5.    ]),
 array([ 7.    ,  7.3   ,  0.65  ,  0.    ,  1.

In [31]:
#converting dataframe directly to a tuple of tuple. I noticed that converting from array of array (df.values) refused to convert
#It is very neccessary to convert the dataframe rows to a tuple to enable it inserted into the sql database
dfTupleRows = tuple(df.itertuples(index=False, name=None))
dfTupleRows

((0, 7.4, 0.7, 0.0, 1.9, 0.076, 11.0, 34.0, 0.9978, 3.51, 0.56, 9.4, 5),
 (1, 7.8, 0.88, 0.0, 2.6, 0.098, 25.0, 67.0, 0.9968, 3.2, 0.68, 9.8, 5),
 (2, 7.8, 0.76, 0.04, 2.3, 0.092, 15.0, 54.0, 0.997, 3.26, 0.65, 9.8, 5),
 (3, 11.2, 0.28, 0.56, 1.9, 0.075, 17.0, 60.0, 0.998, 3.16, 0.58, 9.8, 6),
 (4, 7.4, 0.7, 0.0, 1.9, 0.076, 11.0, 34.0, 0.9978, 3.51, 0.56, 9.4, 5),
 (5, 7.4, 0.66, 0.0, 1.8, 0.075, 13.0, 40.0, 0.9978, 3.51, 0.56, 9.4, 5),
 (6, 7.9, 0.6, 0.06, 1.6, 0.069, 15.0, 59.0, 0.9964, 3.3, 0.46, 9.4, 5),
 (7, 7.3, 0.65, 0.0, 1.2, 0.065, 15.0, 21.0, 0.9946, 3.39, 0.47, 10.0, 7),
 (8, 7.8, 0.58, 0.02, 2.0, 0.073, 9.0, 18.0, 0.9968, 3.36, 0.57, 9.5, 7),
 (10,
  6.7,
  0.58,
  0.08,
  1.8,
  0.0969999999999999,
  15.0,
  65.0,
  0.9959,
  3.28,
  0.54,
  9.2,
  5),
 (12, 5.6, 0.615, 0.0, 1.6, 0.089, 16.0, 59.0, 0.9943, 3.58, 0.52, 9.9, 5),
 (16, 8.5, 0.28, 0.56, 1.8, 0.092, 35.0, 103.0, 0.9969, 3.3, 0.75, 10.5, 7),
 (20, 8.9, 0.22, 0.48, 1.8, 0.077, 29.0, 60.0, 0.9968, 3.39, 0.53, 9.4

In [32]:
#Inserting the tuple into the sql database using cur.executemany cursor to enable it accept both the query and the tuple
insertQuery = "insert into winequality_red values(?,?,?,?,?,?,?,?,?,?,?,?,?)"
cur.executemany(insertQuery, dfTupleRows)

In [33]:
#Using pandas to read my new table in sql database
tableQuery = "select * from winequality_red"
cur.execute(tableQuery)
sqlDF = pd.read_sql_query(tableQuery, conn)
sqlDF

ID  fixedAcidity  volatileAcidity  citricAcid  residualSugar  \
0        0           7.4            0.700        0.00            1.9   
1        1           7.8            0.880        0.00            2.6   
2        2           7.8            0.760        0.04            2.3   
3        3          11.2            0.280        0.56            1.9   
4        4           7.4            0.700        0.00            1.9   
...    ...           ...              ...         ...            ...   
1037  1592           6.3            0.510        0.13            2.3   
1038  1593           6.8            0.620        0.08            1.9   
1039  1594           6.2            0.600        0.08            2.0   
1040  1596           6.3            0.510        0.13            2.3   
1041  1597           5.9            0.645        0.12            2.0   

      chlorides  freeSulfurDioxide  totalSulfurDioxide  density    pH  \
0         0.076                 11                  34  0.99780  3.51   
1         0.098                 25                  67  0.99680  3.20   
2         0.092                 15                  54  0.99700  3.26   
3         0.075                 17                  60  0.99800  3.16   
4         0.076                 11                  34  0.99780  3.51   
...         ...                ...                 ...      ...   ...   
1037      0.076                 29                  40  0.99574  3.42   
1038      0.068                 28                  38  0.99651  3.42   
1039      0.090                 32                  44  0.99490  3.45   
1040      0.076                 29                  40  0.99574  3.42   
1041      0.075                 32                  44  0.99547  3.57   

      sulphates  alcohol  quality  
0          0.56      9.4        5  
1          0.68      9.8        5  
2          0.65      9.8        5  
3          0.58      9.8        6  
4          0.56      9.4        5  
...         ...      ...      ...  
1037       0.75     11.0        6  
1038       0.82      9.5        6  
1039       0.58     10.5        5  
1040       0.75     11.0        6  
1041       0.71     10.2        5  

[1042 rows x 13 columns]

In [39]:
subQuery = "select * from winequality_red where alcohol > 10 order by alcohol desc"
cur.execute(subQuery)
sqlDF2 = pd.read_sql_query(subQuery, conn)
sqlDF2

ID  fixedAcidity  volatileAcidity  citricAcid  residualSugar  \
0     198           5.4            0.835        0.08            1.2   
1    1287           8.0            0.600        0.08            2.6   
2     802           5.1            0.585        0.00            1.7   
3     938           7.2            0.380        0.38            2.8   
4    1052           5.6            0.605        0.05            2.4   
..    ...           ...              ...         ...            ...   
530  1563           7.2            0.695        0.13            2.0   
531  1564           7.2            0.695        0.13            2.0   
532  1567           7.2            0.695        0.13            2.0   
533  1359          11.6            0.475        0.40            1.4   
534  1362          11.6            0.475        0.40            1.4   

     chlorides  freeSulfurDioxide  totalSulfurDioxide  density    pH  \
0        0.046                 13                  93  0.99240  3.57   
1        0.056                  3                   7  0.99286  3.22   
2        0.044                 14                  86  0.99264  3.56   
3        0.068                 23                  42  0.99356  3.34   
4        0.073                 19                  25  0.99258  3.56   
..         ...                ...                 ...      ...   ...   
530      0.076                 12                  20  0.99546  3.29   
531      0.076                 12                  20  0.99546  3.29   
532      0.076                 12                  20  0.99546  3.29   
533      0.091                  6                  28  0.99704  3.07   
534      0.091                  6                  28  0.99704  3.07   

     sulphates    alcohol  quality  
0         0.85  13.000000        7  
1         0.37  13.000000        5  
2         0.94  12.900000        7  
3         0.72  12.900000        7  
4         0.55  12.900000        5  
..         ...        ...      ...  
530       0.54  10.100000        5  
531       0.54  10.100000        5  
532       0.54  10.100000        5  
533       0.65  10.033333        6  
534       0.65  10.033333        6  

[535 rows x 13 columns]

In [40]:
allTablesQuery = "select name from sqlite_master where type = 'table'"
cur.execute(allTablesQuery)
print(cur.fetchall())

[('instructor',), ('daibetes',), ('diamonds',), ('winequality_red',)]
